export const EXAMPLE_GET_QUERY_KEY = "example-get";
export const GET_USER_PROFILE_QUERY_KEY = "GET_USER_PROFILE_QUERY_KEY";

// Notification query keys
export const GET_NOTIFICATIONS_QUERY_KEY = "GET_NOTIFICATIONS_QUERY_KEY";
export const GET_UNREAD_COUNT_QUERY_KEY = "GET_UNREAD_COUNT_QUERY_KEY";
export const GET_NOTIFICATION_COUNTS_QUERY_KEY = "GET_NOTIFICATION_COUNTS_QUERY_KEY";
export const GET_NOTIFICATION_PREFERENCES_QUERY_KEY =
  "GET_NOTIFICATION_PREFERENCES_QUERY_KEY";
